# Sign UP
GET http://localhost:7500/allUsers
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiItbGl2d0x1dGdqa0xLbGpKdml6bDAiLCJpYXQiOjE2MzgxMTc0NTV9.4v4Me-5vJTS3I7ORVYNyu0FXcsx3Ec0fbjB99Hjp9h0


###

# GET COURSES
GET http://localhost:7500/api/admins/courses
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJ4ZUdJc1J1QzlDaTFXUnQ3SjgwX2MiLCJpYXQiOjE2MzgzNzY4MTR9.8gzgGVKAm4cFDuuwdVNU6IlJhUY5yrErKiT7ouvWJx0


###